import { Inter } from "next/font/google";
import type { Metadata } from "next";
import "./globals.css";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "RunDataAnalisys",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: { lang: string };
}) {
  
  const lang = params.lang || "en"; 
  
  return (
    <html lang={lang}>
      <Head>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body className={`flex ${inter.className}`}>
        {children}       
      </body>
    </html>
  );
}